# Generated by Django 4.2.11 on 2025-04-12 04:08

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColumnMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("NUMBER", "Number"),
                            ("EMAIL", "Email"),
                            ("PHONE", "Phone"),
                            ("DATE", "Date"),
                            ("BOOLEAN", "Boolean"),
                            ("SELECT", "Select"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("default_value", models.TextField(blank=True, null=True)),
                (
                    "options",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated options for SELECT field type",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Custom Field",
                "verbose_name_plural": "Custom Fields",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="custom_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AddField(
            model_name="fileimport",
            name="mapping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imports",
                to="customer.columnmapping",
            ),
        ),
        migrations.CreateModel(
            name="MappingField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_column", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[("base", "Base Field"), ("custom", "Custom Field")],
                        max_length=10,
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                ("is_required", models.BooleanField(default=False)),
                ("default_value", models.TextField(blank=True, null=True)),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="customer.columnmapping",
                    ),
                ),
            ],
            options={
                "ordering": ["mapping", "csv_column"],
                "unique_together": {("mapping", "csv_column")},
            },
        ),
    ]
