# Generated by Django 4.2.11 on 2025-04-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_columnmapping_customerfield_customer_custom_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="area",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INVALID", "Invalid"),
                    ("VALID", "Valid"),
                    ("CALL_NOT_ATTENDED", "Call Not Attended"),
                    ("PLAN_PRESENTED", "Plan Presented"),
                    ("INTERESTED", "Interested"),
                    ("NOT_INTERESTED", "Not Interested"),
                    ("FOLLOW_UP", "Follow Up"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("CAMPUS_VISIT", "Campus Visit"),
                    ("REGISTRATION", "Registration"),
                    ("ADMISSION", "Admission"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customerstatushistory",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("INVALID", "Invalid"),
                    ("VALID", "Valid"),
                    ("CALL_NOT_ATTENDED", "Call Not Attended"),
                    ("PLAN_PRESENTED", "Plan Presented"),
                    ("INTERESTED", "Interested"),
                    ("NOT_INTERESTED", "Not Interested"),
                    ("FOLLOW_UP", "Follow Up"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("CAMPUS_VISIT", "Campus Visit"),
                    ("REGISTRATION", "Registration"),
                    ("ADMISSION", "Admission"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customerstatushistory",
            name="previous_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INVALID", "Invalid"),
                    ("VALID", "Valid"),
                    ("CALL_NOT_ATTENDED", "Call Not Attended"),
                    ("PLAN_PRESENTED", "Plan Presented"),
                    ("INTERESTED", "Interested"),
                    ("NOT_INTERESTED", "Not Interested"),
                    ("FOLLOW_UP", "Follow Up"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("CAMPUS_VISIT", "Campus Visit"),
                    ("REGISTRATION", "Registration"),
                    ("ADMISSION", "Admission"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("manager", "Sales Manager"), ("sales", "Student Counsellor")],
                default="sales",
                max_length=10,
            ),
        ),
    ]
