# Generated by Django 4.2.11 on 2025-04-12 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_customer_area_customer_date_customer_remark_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="columnmapping",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="CustomerField",
        ),
        migrations.AlterUniqueTogether(
            name="mappingfield",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="mappingfield",
            name="mapping",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="custom_data",
        ),
        migrations.RemoveField(
            model_name="fileimport",
            name="mapping",
        ),
        migrations.DeleteModel(
            name="ColumnMapping",
        ),
        migrations.DeleteModel(
            name="MappingField",
        ),
    ]
