# Generated by Django 4.2.11 on 2025-04-12 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_remove_customer_email_remove_customer_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="area",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INVALID", "Invalid"),
                    ("VALID", "Valid"),
                    ("CALL_NOT_ATTENDED", "Call Not Attended"),
                    ("PLAN_PRESENTED", "Plan Presented"),
                    ("INTERESTED", "Interested"),
                    ("NOT_INTERESTED", "Not Interested"),
                    ("FOLLOW_UP", "Follow Up"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("CAMPUS_VISIT", "Campus Visit"),
                    ("REGISTRATION", "Registration"),
                    ("ADMISSION", "Admission"),
                ],
                db_index=True,
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customerstatushistory",
            name="changed_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="customerstatushistory",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("INVALID", "Invalid"),
                    ("VALID", "Valid"),
                    ("CALL_NOT_ATTENDED", "Call Not Attended"),
                    ("PLAN_PRESENTED", "Plan Presented"),
                    ("INTERESTED", "Interested"),
                    ("NOT_INTERESTED", "Not Interested"),
                    ("FOLLOW_UP", "Follow Up"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("CAMPUS_VISIT", "Campus Visit"),
                    ("REGISTRATION", "Registration"),
                    ("ADMISSION", "Admission"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customerstatushistory",
            name="previous_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INVALID", "Invalid"),
                    ("VALID", "Valid"),
                    ("CALL_NOT_ATTENDED", "Call Not Attended"),
                    ("PLAN_PRESENTED", "Plan Presented"),
                    ("INTERESTED", "Interested"),
                    ("NOT_INTERESTED", "Not Interested"),
                    ("FOLLOW_UP", "Follow Up"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("CAMPUS_VISIT", "Campus Visit"),
                    ("REGISTRATION", "Registration"),
                    ("ADMISSION", "Admission"),
                ],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
    ]
