# Generated by Django 4.2.11 on 2025-04-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_alter_customer_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["name", "-created_at"]},
        ),
    ]
