# Generated by Django 4.2.11 on 2025-04-23 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_alter_customer_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerstatushistory",
            options={},
        ),
        migrations.CreateModel(
            name="FollowUpReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("follow_up_date", models.DateField(db_index=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_up_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="customer.customer",
                    ),
                ),
                (
                    "status_history",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_up_reminder",
                        to="customer.customerstatushistory",
                    ),
                ),
            ],
            options={
                "ordering": ["follow_up_date", "-created_at"],
            },
        ),
    ]
