# Generated by Django 4.2.11 on 2025-04-14 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_merge_0007_alter_customer_name_add_customer_notes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NoteCategory",
        ),
    ]
